### ISSUE TITLE
[Request] uMod

### ISSUE THREAD

**Issue by LadyViktoria** [Zinal001/ValheimMods#1]
hi
can you port this to uMod as well?

**Comment by Zinal001** [comment]
I'll have a look. Never used uMod before but it shouldn't be to much trouble as far as I can tell.

**Comment by Bigfoot129012** [comment]
this will not work on my valheim server would like some help please

**Comment by Bigfoot129012** [comment]
[Debug  :Server Messages] Checking 0 FixedTimedMessages
[Debug  :Server Messages] Checking 0 FixedTimedMessages
[Debug  :Server Messages] Checking 0 FixedTimedMessages
this is what i set it to
<Message>
    <Type>TimedMessage</Type> 
    <Enabled>True</Enabled> 
    <Sender>Server</Sender> 
    <Text>The server Welcome we have updated the server files please download them at https://www.bigfootsgaming.com/valheim/ today!</Text> 
    <Start_At>2021-02-28 03:00:00</Start_At> 
    <Duration_Between>00:30:00</Duration_Between> 
    <End_At>2021-03-08 24:00:00</End_At> 
  </Message>

still not working

**Comment by LadyViktoria** [comment]
nevermind found a umod that could do random server messages. thanks for your work

**Comment by Bigfoot129012** [comment]
> nevermind found a umod that could do random server messages. thanks for your work

what are you useing i would like to have it it this one does not work please and thanks
