### ISSUE TITLE
TimedMessage show time

### ISSUE THREAD

**Issue by Lime18** [Zinal001/ValheimMods#5]
Hi, add a time setting to the TimedMessage, after which time interval to show messages.
ShowTime = 120 //Display a message every 60 seconds.

**Comment by Zinal001** [comment]
Ehum.. That's what the **DurationBetween** property is for? A **DurationBetween** property of `"00:10:00"` for example means the the message will be sent every 10 minutes.

**Comment by Lime18** [comment]
I did not understand the description correctly, thank you very much)
